SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3
FRAMES_AFTER_HIT = 50  # frames after the player was hit

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds

EXPLOSION_RADIUS = 50
EXPLOSION_DURATION = 0.3  # seconds

POWERUP_RADIUS = 30
POWERUP_SPAWN_RATE = 5  # seconds
POWERUP_SHAPE_DURATION = 8  # seconds
POWERUP_LIFESPAN = 5  # seconds
POWERUP_TYPES = {
    "shield": 0,
    "nuke": 0,
    "laser": 0,
    "triple_shot": 1,
}
